name: Controls
description: Some positive and negative control methods
authors:
  - name: Wouter Saelens
    roles:
      - Conceptualization
      - Methodology
      - Software
    orcid: 0000-0002-7114-6248